on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Run Tox tests on PraxeRedhat2023

jobs:
  tox_test:
    name: Tox test
    strategy:
      matrix:
        tox_env: [py36, py37, py38, py39, py310]
    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests on PraxeRedhat2023
      id: test
      uses: fedora-python/tox-github-action@master
      with:
        tox_env: ${{ matrix.tox_env }}
        dnf_install: gcc rpm-devel git python3-devel
